### ISSUE TITLE
A bug in reading GCode text file with M117 command

### ISSUE THREAD

**Issue by dudugabay** [chrismiller7/GCodeNet#1]
Hello, 
I am trying to read with this software a gcode text file which contains this line:
M117 Printing...

and the code throws exception at GCodeTokenizer.cs line 106.

Am I doing something wrong here..?

**Comment by chrismiller7** [comment]
Thanks for the feedback. It looks like I did not account for this type of command. The problem is that the M117 command follows different formatting rules than most of the other command types: Contains a string, allows whitespace, and doesn't contain a Parameter Type(X,Y,F,etc). I will work on this.

**Comment by chrismiller7** [comment]
Also, if you could send me the gcode file you are working with, I would be able to test this better.

**Comment by chrismiller7** [comment]
I updated the library to allow for the M117 command.
